fix bug when commit fragment transaction
bug flow
1. register callback which contain <transaction.commit()>
2. before callback is called, get out of screen (call onSaveInstanceState() activity code)
3. then error
> java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

fix
1. call commit -> call commitAllowingStateLoss
(https://developer.android.com/reference/android/app/FragmentTransaction.html#commitAllowingStateLoss())